### ISSUE TITLE
No module named 'onnx'

### ISSUE THREAD

**Issue by moonwhaler** [fireicewolf/wd-joy-caption-cli#1]
I followed the instructions by the book (I think) and installed the requirements.txt for ONNX (CuDNN 12):

`pip install -U -r requirements_onnx_cu12x.txt
Requirement already satisfied: onnxruntime-gpu==1.19.0 in ./venv/lib/python3.10/site-packages (from -r requirements_onnx_cu12x.txt (line 1)) (1.19.0)
Requirement already satisfied: numpy>=1.21.6 in ./venv/lib/python3.10/site-packages (from onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (1.26.4)
Requirement already satisfied: coloredlogs in ./venv/lib/python3.10/site-packages (from onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (15.0.1)
Requirement already satisfied: protobuf in ./venv/lib/python3.10/site-packages (from onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (5.28.0)
Requirement already satisfied: flatbuffers in ./venv/lib/python3.10/site-packages (from onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (24.3.25)
Requirement already satisfied: sympy in ./venv/lib/python3.10/site-packages (from onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (1.12)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (24.1)
Requirement already satisfied: humanfriendly>=9.1 in ./venv/lib/python3.10/site-packages (from coloredlogs->onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (10.0)
Requirement already satisfied: mpmath>=0.19 in ./venv/lib/python3.10/site-packages (from sympy->onnxruntime-gpu==1.19.0->-r requirements_onnx_cu12x.txt (line 1)) (1.3.0)`

But when running "caption.py" inside venv I get:

`Details: No module named 'onnx'
Traceback (most recent call last):
  File "/home/christian/AI/wd-joy-caption-cli/utils/inference.py", line 374, in load_model
    import onnx
ModuleNotFoundError: No module named 'onnx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/christian/AI/wd-joy-caption-cli/caption.py", line 537, in <module>
    main(get_args)
  File "/home/christian/AI/wd-joy-caption-cli/caption.py", line 136, in main
    my_tagger.load_model()
  File "/home/christian/AI/wd-joy-caption-cli/utils/inference.py", line 378, in load_model
    raise ImportError
ImportError`

Thank you.

**Comment by fireicewolf** [comment]
`onnx` and `onnxruntime` are under `requirements_wd.txt`, maybe you only installed `onnxruntime-gpu` via `requirements_onnx_cu12x.txt`?
WD series models need `onnx` and `onnxruntime`(`onnxruntime-gpu` is optional unless you want to run wd inference with GPU)

**Comment by moonwhaler** [comment]
That did it. Thank you!
