### ISSUE TITLE
Prompting with images is incompatible with system messages

### ISSUE THREAD

**Issue by D3voz** [fireicewolf/wd-joy-caption-cli#3]
2024-10-01 11:39:09,190 - inference.py[line:283] - ERROR: Failed to caption image: F:\img\Fern\25859072.jpg, skip it.
error info: Prompting with images is incompatible with system messages.
Processing: F:\img\Fern\25859072.jpg ... mg\Fern\25859072.jpg:   0%|                            | 0/19 [00:00<?, ?it/s]
2024-10-01 11:39:09,191 - inference.py[line:294] - INFO: Unloading LLM...
2024-10-01 11:39:09,193 - inference.py[line:299] - INFO: LLM unloaded in 0.0s.

Tried with - python caption.py F:\img\Fern --caption_method llama

**Comment by fireicewolf** [comment]
Meta has update their chat_template, while using images with system_prompt, will raise this error.
To avoid this, you need to change the `chat_template.json`
Found these in `chat_template.json`
```
{%- if content['type'] == 'image' %}\n            {%- set image_ns.has_images = true %}\n
``` 
Change to
```
{%- if content['type'] == 'image' %}\n            {%- set image_ns.has_images = false %}\n
``` 

I may add replacement in my code later.
